// Every string the Shell shows a person, in the two languages it speaks. One table, two columns:
// `en` is typed as `zh`, so a key missing from either is a type error, not a blank on a page.
// The zh column says the glossary's display names (CONTEXT.md, `_Shown as_`); the en column
// says the glossary's own words. Keys that need a number or a name in them are arrow functions —
// no placeholder grammar, and en's plurals are the function's own business. Each one is shipped
// to the comment client as its own source, so it may close over nothing: no shared helper, no
// other key. Nothing here is for an agent: the API's errors, the skill and the webhook stay English.
import type { IncomingMessage } from 'node:http';

export type Lang = 'zh' | 'en';

const zh = {
  untitled: '未命名',
  back: '← 返回',
  readOnly: '只读',
  frozenHere: '冻结在此版',
  frozenAt: (n: number) => `冻结在 v${n}`,
  loading: '页面加载中',
  collapse: '收起',
  dead: '链接已失效',
  askPublisher: '请向发布方索取新的链接。',
  gallery: '画廊',
  members: '成员',
  logout: '退出',
  notFound: '找不到',
  artifactNotFound: '找不到这个工件。它可能已经被删除。',
  pasteToken: '贴上你的令牌',
  enter: '进入',
  badToken: '这个令牌用不了：可能贴错了，或者已被撤销。',
  noArtifacts: '还没有工件。用令牌发一版，它就出现在这里。',
  title: '标题',
  client: '客户',
  latest: '最新版',
  openAnnotations: '未解决批注',
  readers: '收件人',
  lastPublished: '最近发布',
  version: '版本',
  versions: '版本',
  canvas: '画布宽度',
  published: '发布',
  frozen: '冻结中',
  unfreeze: '解冻',
  openN: (n: number) => `未解决 ${n}`,
  addressedN: (n: number) => `已解决 ${n}`,
  noOpen: '没有未解决的批注。',
  noAddressed: '没有已解决的批注。',
  reader: '收件人',
  text: '正文',
  time: '时间',
  notCurrent: '（非当前版）',
  readerName: '收件人的名字，建后不可改',
  makeLink: '建链接',
  noReaders: '还没有收件人链接。',
  name: '名字',
  link: '链接',
  created: '建立',
  revoked: '已撤销',
  copy: '复制',
  revokeReaderAsk: (name: string) => `撤销「${name}」的链接？这条链接立刻失效，且不可恢复。`,
  clientIs: (client: string) => `客户 ${client}`,
  canvasIs: (px: number) => `画布 ${px}px`,
  deleteArtifact: '删除工件',
  deleteArtifactAsk: (title: string) => `删除「${title}」？所有收件人链接立刻失效，且不可恢复。`,
  newToken: '新令牌',
  onlyOnce: '这串明文只出现这一次，关掉就没有了。',
  memberName: '名字，会记在每一版上',
  clientOptional: '客户（可空，留空即内部）',
  mint: '发令牌',
  membersInternalOnly: '成员页只对内部令牌开放。',
  /** What the comment client reads: shipped into the Shell page as `T`, and nothing more than it reads. */
  shell: {
    nameSetByPublisher: '名字由发布方设定',
    annotate: '批注',
    annotations: '批注',
    allAnnotations: '全部批注',
    allAnnotationsN: (n: number) => `全部批注 ${n}`,
    justNow: '刚刚',
    draftPending: '先发出或丢弃正在写的批注',
    exitMode: '退出批注模式',
    byReader: (name: string) => `${name} 的批注`,
    draftLabel: '正在写的批注',
    above: (n: number) => `还有 ${n} 条批注在上方`,
    below: (n: number) => `还有 ${n} 条批注在下方`,
    detached: '位置已失效',
    pinnedOn: (n: number, same: boolean) => `钉在 v${n} 上${same ? '，这一版找不到原位置' : ''}`,
    open: '未解决',
    addressed: '已解决',
    del: '删除',
    markAddressed: '标为已解决',
    reopen: '重新打开',
    close: '关闭',
    deleteAnnotationAsk: '删除这条批注？',
    writeSomething: '写点什么…',
    discard: '丢弃',
    send: '发出',
    sent: '已发出',
    openCount: (n: number) => `${n} 条未解决`,
    allAddressed: '全部已解决',
    noAnnotations: '还没有批注。',
    noAnnotationsYet: '还没有批注。点右上角的批注按钮，再点页面上任意位置。',
    onPage: '页面上的批注',
    notShown: '未在页面上显示',
    hideAddressed: '隐藏已解决',
    showAddressed: (n: number) => `显示 ${n} 条已解决`,
    modeHint: '点一下进入批注模式 (c)',
    notReady: '页面没有就绪，无法批注',
    saveAsk: '这一页想保存一个文件',
    cancel: '取消',
    save: '保存',
  },
  /** What the Publisher pages' own script reads, shipped the same way. */
  pub: {
    copied: '已复制',
    httpFailed: (status: number) => `没成功（HTTP ${status}）`,
    revoke: '撤销',
    mintFailed: (reason: string) => `发令牌没成功：${reason}`,
    revokeTokenAsk: (name: string) => `撤销「${name}」？它的 API 调用和浏览器会话立刻断开，且不可恢复。`,
  },
};

const en: typeof zh = {
  untitled: 'Untitled',
  back: '← Back',
  readOnly: 'Read-only',
  frozenHere: 'Frozen at this version',
  frozenAt: (n) => `Frozen at v${n}`,
  loading: 'Page loading',
  collapse: 'Close',
  dead: 'This link is no longer valid',
  askPublisher: 'Ask the Publisher for a new link.',
  gallery: 'Gallery',
  members: 'Members',
  logout: 'Log out',
  notFound: 'Not found',
  artifactNotFound: 'This Artifact cannot be found. It may have been deleted.',
  pasteToken: 'Paste your token',
  enter: 'Enter',
  badToken: 'That token does not work: it may be mistyped, or revoked.',
  noArtifacts: 'No Artifacts yet. Publish one with a token and it appears here.',
  title: 'Title',
  client: 'Client',
  latest: 'Latest',
  openAnnotations: 'Open annotations',
  readers: 'Readers',
  lastPublished: 'Last published',
  version: 'Version',
  versions: 'Versions',
  canvas: 'Canvas',
  published: 'Published',
  frozen: 'Frozen',
  unfreeze: 'Unfreeze',
  openN: (n) => `Open ${n}`,
  addressedN: (n) => `Addressed ${n}`,
  noOpen: 'No open annotations.',
  noAddressed: 'No addressed annotations.',
  reader: 'Reader',
  text: 'Text',
  time: 'Time',
  notCurrent: '(not the current version)',
  readerName: 'The Reader’s name; it cannot be changed later',
  makeLink: 'Create link',
  noReaders: 'No Reader links yet.',
  name: 'Name',
  link: 'Link',
  created: 'Created',
  revoked: 'Revoked',
  copy: 'Copy',
  revokeReaderAsk: (name) => `Revoke the link for “${name}”? It stops working immediately and cannot be restored.`,
  clientIs: (client) => `Client ${client}`,
  canvasIs: (px) => `Canvas ${px}px`,
  deleteArtifact: 'Delete Artifact',
  deleteArtifactAsk: (title) => `Delete “${title}”? Every Reader link stops working immediately and cannot be restored.`,
  newToken: 'New token',
  onlyOnce: 'The plaintext is shown this once; close it and it is gone.',
  memberName: 'Name, recorded on every Version',
  clientOptional: 'Client (optional; blank means internal)',
  mint: 'Mint token',
  membersInternalOnly: 'The members page is for internal tokens only.',
  /** What the comment client reads: shipped into the Shell page as `T`, and nothing more than it reads. */
  shell: {
    nameSetByPublisher: 'Name set by the Publisher',
    annotate: 'Annotate',
    annotations: 'Annotations',
    allAnnotations: 'All annotations',
    allAnnotationsN: (n) => `All annotations · ${n}`,
    justNow: 'just now',
    draftPending: 'Send or discard the annotation you are writing first',
    exitMode: 'Exit annotation mode',
    byReader: (name) => `Annotation by ${name}`,
    draftLabel: 'Annotation being written',
    above: (n) => `${n} annotation${n === 1 ? '' : 's'} above`,
    below: (n) => `${n} annotation${n === 1 ? '' : 's'} below`,
    detached: 'Detached',
    pinnedOn: (n, same) => `Pinned on v${n}${same ? ', its place not found on this version' : ''}`,
    open: 'Open',
    addressed: 'Addressed',
    del: 'Delete',
    markAddressed: 'Mark addressed',
    reopen: 'Reopen',
    close: 'Close',
    deleteAnnotationAsk: 'Delete this annotation?',
    writeSomething: 'Write something…',
    discard: 'Discard',
    send: 'Send',
    sent: 'Sent',
    openCount: (n) => `${n} open`,
    allAddressed: 'All addressed',
    noAnnotations: 'No annotations yet.',
    noAnnotationsYet: 'No annotations yet. Press Annotate at the top right, then click anywhere on the page.',
    onPage: 'On the page',
    notShown: 'Not shown on page',
    hideAddressed: 'Hide addressed',
    showAddressed: (n) => `Show ${n} addressed`,
    modeHint: 'Click to enter annotation mode (c)',
    notReady: 'The page did not become ready; annotating is unavailable',
    saveAsk: 'This page wants to save a file',
    cancel: 'Cancel',
    save: 'Save',
  },
  /** What the Publisher pages' own script reads, shipped the same way. */
  pub: {
    copied: 'Copied',
    httpFailed: (status) => `Failed (HTTP ${status})`,
    revoke: 'Revoke',
    mintFailed: (reason) => `Minting failed: ${reason}`,
    revokeTokenAsk: (name) => `Revoke “${name}”? Its API calls and browser session stop immediately and cannot be restored.`,
  },
};

export type Strings = typeof zh;
export const STRINGS: Record<Lang, Strings> = { zh, en };

/**
 * The one resolution rule, for every page (spec): `?lang=` when it names a language we have, else
 * the first `Accept-Language` tag that starts with one, else Chinese — most first opens are in
 * WeChat. Nothing is remembered: no cookie, no column, so a refresh follows the browser again.
 */
export function langOf(url: URL, req: IncomingMessage): Lang {
  const asked = url.searchParams.get('lang');
  if (asked === 'zh' || asked === 'en') return asked;
  for (const tag of (req.headers['accept-language'] ?? '').split(',')) {
    const prefix = tag.trim().slice(0, 2).toLowerCase();
    if (prefix === 'zh' || prefix === 'en') return prefix;
  }
  return 'zh';
}
